name: portal8
description: Exit the Matrix by Entering Within. Portal 8 is your journey from illusion to inner awakening.
publish_to: 'none'
version: 4.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  vibration: ^1.7.4

  firebase_auth: ^4.17.0
  firebase_core: ^2.24.2
  google_sign_in: 6.1.0
  animated_text_kit: ^4.2.2
  url_launcher: ^6.1.10
  auto_size_text: ^3.0.0
  http: ^1.1.0
  geolocator: ^10.0.0
  flutter_stripe: ^9.0.0
  ip_country_lookup: ^1.0.0
  webview_flutter: ^4.2.2

  firebase_remote_config: ^4.2.0


  cloud_functions: ^4.5.2
  provider: ^6.1.1
  audioplayers: ^5.2.1
  shared_preferences: ^2.2.2
  google_fonts: ^6.1.0
  razorpay_flutter: ^1.3.5
  percent_indicator: ^4.2.3
  flutter_svg: ^2.0.10+1
  page_transition: ^2.1.0
  cloud_firestore: ^4.13.1
  flutter_dotenv: ^5.1.0
  file_picker: ^6.1.1










dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/portals/portal_data.json
    - assets/portals/portal1.json
    - assets/portals/portal2.json
    - assets/portals/portal3.json
    - assets/portals/portal4.json
    - assets/portals/portal5.json
    - assets/portals/portal6.json
    - assets/portals/portal7.json
    - assets/portals/portal8.json
    - assets/data/portal0_chapters.json
    - assets/images/
    - assets/audio/
    - assets/google.png
    - assets/particles.gif
    - assets/sounds/cosmic_chime.mp3
    - assets/audio/infinity_ambience.mp3
    - assets/advanced_practices.json
    - assets/infinite_scroll.json
    - assets/infinity_scroll.json
    - .env







  fonts:
    - family: Orbitron
      fonts:
        - asset: assets/fonts/Orbitron-Regular.ttf
        - asset: assets/fonts/Orbitron-Bold.ttf
          weight: 700

    - family: PortalLogoFont
      fonts:
        - asset: assets/fonts/PortalFont.ttf
