// File generated by FlutterFire CLI, customized for Cashfree config
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps + Cashfree config
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDoAsxo75-GrCGTwbuYc_qNwH8YGpJBos',
    appId: '1:58466283676:web:c887b70d4c095d0fafbd59',
    messagingSenderId: '58466283676',
    projectId: 'portal8-582w8',
    authDomain: 'portal8-582w8.firebaseapp.com',
    storageBucket: 'portal8-582w8.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQjdK2NHREOQG6sePijTSPTnY8JIU3QNY',
    appId: '1:58466283676:android:b24c01743932d003afbd59',
    messagingSenderId: '58466283676',
    projectId: 'portal8-582w8',
    storageBucket: 'portal8-582w8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJA2VqxsAdKJPlr5gnbt5agF_ocbhrrDw',
    appId: '1:58466283676:ios:114a14e24158f31aafbd59',
    messagingSenderId: '58466283676',
    projectId: 'portal8-582w8',
    storageBucket: 'portal8-582w8.firebasestorage.app',
    iosClientId: '58466283676-ilpijtm4j4f5r55dvc1hdh7tme165hfh.apps.googleusercontent.com',
    iosBundleId: 'com.portal8.app.portal8',
  );
}

/// 🔑 Cashfree Config (Sandbox + Live)
class CashfreeConfig {
  // Sandbox
  static const String sandboxAppId =
      "TEST1076438780975e669d4f3eb93e0078346701";
  static const String sandboxSecretKey =
      "cfsk_ma_test_50c971d390445e976c89b6af93bb0e66_bb845860";
  static const String sandboxUrl =
      "https://sandbox.cashfree.com/api/v2/cftoken/order";

  // Live
  static const String liveAppId = "1052539ab0c917ffef40b39217e9352501";
  static const String liveSecretKey =
      "cfsk_ma_prod_ecf3f71fcb38b2c6ccaa0c56141d28aa_37295b44";
  static const String liveUrl =
      "https://api.cashfree.com/api/v2/cftoken/order";

  /// Switch automatically: if app is in Release → use live, otherwise sandbox
  static bool get isLive => const bool.fromEnvironment("dart.vm.product");

  static String get appId => isLive ? liveAppId : sandboxAppId;
  static String get secretKey => isLive ? liveSecretKey : sandboxSecretKey;
  static String get url => isLive ? liveUrl : sandboxUrl;
}
